version: '3.0'

services:
  db:
    image: mysql:8
    container_name: appraisal_db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=appraisal
      - MYSQL_USER=app_user
      - MYSQL_PASSWORD=abc123
    ports:
      - 3306:3306
